security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api
            stateless: true
            jwt: ~
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\GandalfAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # pour eviter les boucles infinies de redirection
        # on met toujours la page de login en premier et en public
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        
        # /back/casting/{id}/edit 
        - { path: ^\/back\/\w+\/\d+\/edit$, roles: ROLE_ADMIN }
        # ? https://symfony.com/doc/5.4/security/access_control.html
        # POST /back/casting/{id} 
        - { path: ^\/back\/\w+\/\d+$, roles: ROLE_ADMIN , methods: [POST] }
        # GET /back/casting/{id} 
        - { path: ^\/back\/\w+\/\d+$, roles: ROLE_MANAGER, methods: [GET] }
        # /back/casting/new
        - { path: ^\/back\/\w+\/new$, roles: ROLE_ADMIN }
        # /back/casting/
        - { path: ^\/back\/\w+\/$, roles: ROLE_MANAGER }
        
        # /back/movie , /back/main 
        - { path: ^/back, roles: ROLE_MANAGER }
        # /movies/999/review/add
        # - { path: ^\/movies\/\d+\/review\/add$, roles: ROLE_USER }
        - { path: ^/movies/\d+/review/add$, roles: ROLE_USER }
        # /movies/999
        - { path: ^\/movies\/\d+$, roles: PUBLIC_ACCESS }
        # potentiellement inutile si toutes les autres URL sont restreintes
        - { path: ^/, roles: PUBLIC_ACCESS }

    role_hierarchy:
        # le ROLE_ADMIN inclus le ROLE_MANAGER
        ROLE_ADMIN:   ROLE_MANAGER
        # le ROLE_MANAGER inclus le ROLE_USER
        ROLE_MANAGER: [ROLE_USER, ROLE_CLIENT]
        # * donc le ROLE_ADMIN inclus le ROLE_USER et le ROLE_CLIENT

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
